#cloud-config

---
coreos:

  locksmith:
    endpoint: https://etcd.${ internal-tld }:2379
    etcd_cafile: /etc/kubernetes/ssl/ca.pem
    etcd_certfile: /etc/kubernetes/ssl/k8s-bastion.pem
    etcd_keyfile: /etc/kubernetes/ssl/k8s-bastion-key.pem

  update:
    reboot-strategy: off

  units:
    - name: download-etcdctl3.service
      command: start
      content: |
        [Unit]
        After=network-online.target
        Requires=network-online.target
        Before=etcd-member.service
        Description=Download etcdctl3
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/opt/bin/download-etcdctl-v3 ${ etcd-version }

write-files:
  - path: /etc/kubernetes/ssl/ca.pem
    content: ${ ca-pem }
    permissions: '0644'
    encoding: base64

  - path: /etc/kubernetes/ssl/k8s-bastion-key.pem
    content: ${ bastion-key }
    encoding: base64
    permissions: '0644'
    owner: root

  - path: /etc/kubernetes/ssl/k8s-bastion.pem
    content: ${ bastion-pem }
    permissions: '0644'
    encoding: base64

  - path: /etc/environment
    permissions: 0644
    content: |
      ETCDCTL_CA_FILE=/etc/kubernetes/ssl/ca.pem
      ETCDCTL_CERT_FILE=/etc/kubernetes/ssl/k8s-bastion.pem
      ETCDCTL_ENDPOINTS=https://etcd.${ internal-tld }:2379
      ETCDCTL_KEY_FILE=/etc/kubernetes/ssl/k8s-bastion-key.pem

  - path: /opt/bin/download-etcdctl-v3
    permissions: 0755
    owner: root:root
    content: |
      #!/bin/bash -e
      curl -o etcd.tar.gz -SL https://github.com/coreos/etcd/releases/download/v$1/etcd-v$1-linux-amd64.tar.gz
      tar -zxvf etcd.tar.gz etcd-v$1-linux-amd64/etcdctl
      mv etcd-v$1-linux-amd64/etcdctl /opt/bin/etcdctl3
      chmod +x /opt/bin/etcdctl3
      rm -rf  etcd-v$1-linux-amd64 etcd.tar.gz