#cloud-config

---
coreos:

  flannel:
    interface: $private_ipv4
    etcd_cafile: /etc/kubernetes/ssl/ca.pem
    etcd_certfile: /etc/kubernetes/ssl/k8s-etcd.pem
    etcd_keyfile: /etc/kubernetes/ssl/k8s-etcd-key.pem
    etcd_endpoints: https://etcd.${ internal-tld }:2379

  units:

    - name: download-etcdctl3.service
      command: start
      content: |
        [Unit]
        After=network-online.target
        Requires=network-online.target
        Before=etcd-member.service
        Description=Download etcdctl3
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/opt/bin/download-etcdctl-v3 ${ etcd-version }

    - name: etcd-member.service
      command: start
      drop-ins:

        - name: 10-environment.conf
          content: |
            [Service]
            Environment="ETCD_IMAGE_TAG=v${ etcd-version }"
            Environment="ETCD_ADVERTISE_CLIENT_URLS=https://${ fqdn }:2379"
            Environment="ETCD_CERT_FILE=/etc/ssl/certs/k8s-etcd.pem"
            Environment="ETCD_CLIENT_CERT_AUTH=true"
            Environment="ETCD_DISCOVERY_SRV=${ internal-tld }"
            Environment="ETCD_INITIAL_ADVERTISE_PEER_URLS=https://${ fqdn }:2380"
            Environment="ETCD_INITIAL_CLUSTER_STATE=new"
            Environment="ETCD_INITIAL_CLUSTER_TOKEN=${ cluster-token }"
            Environment="ETCD_KEY_FILE=/etc/ssl/certs/k8s-etcd-key.pem"
            Environment="ETCD_LISTEN_CLIENT_URLS=https://0.0.0.0:2379"
            Environment="ETCD_LISTEN_PEER_URLS=https://0.0.0.0:2380"
            Environment="ETCD_NAME=${ hostname }"
            Environment="ETCD_PEER_CERT_FILE=/etc/ssl/certs/k8s-etcd.pem"
            Environment="ETCD_PEER_KEY_FILE=/etc/ssl/certs/k8s-etcd-key.pem"
            Environment="ETCD_PEER_TRUSTED_CA_FILE=/etc/ssl/certs/ca.pem"
            Environment="ETCD_SSL_DIR=/etc/kubernetes/ssl"
            Environment="ETCD_TRUSTED_CA_FILE=/etc/ssl/certs/ca.pem"

    - name: flanneld.service
      command: start
      drop-ins:
        - name: 50-network-config.conf
          content: |
            [Unit]
            Wants=network-online.target
            After=network-online.target
            [Service]
            EnvironmentFile=/etc/environment
            Environment="ETCD_SSL_DIR=/etc/kubernetes/ssl"
            ExecStartPre=-/usr/bin/etcdctl mk /coreos.com/network/config \
              '{ "Network": "${ pod-ip-range }", "Backend": { "Type": "vxlan" } }'
            Restart=always
            RestartSec=10

    - name: docker.service
      command: start
      drop-ins:
        - name: 40-flannel.conf
          content: |
            [Unit]
            After=flanneld.service
            Requires=flanneld.service
            [Service]
            Restart=always
            RestartSec=10

    - name: prefetch-rkt-hyperkube.service
      command: start
      content: |
        [Unit]
        After=network-online.target
        Requires=network-online.target
        Description=Prefetch rkt Hyperkube
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStartPre=/usr/bin/rkt trust --trust-keys-from-https --prefix=quay.io/coreos/hyperkube
        ExecStart=/usr/bin/rkt fetch ${ hyperkube-image }:${ hyperkube-tag }

    - name: prefetch-docker-hyperkube.service
      command: start
      content: |
        [Unit]
        After=docker.service
        Requires=docker.service
        Description=Prefetch docker Hyperkube
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/usr/bin/docker pull ${ hyperkube }

    - name: kubelet.service
      command: start
      runtime: true
      content: |
        [Unit]
        ConditionFileNotEmpty=/etc/kubernetes/ssl/service-account-key.pem
        ConditionFileIsExecutable=/usr/lib/coreos/kubelet-wrapper
        After=flanneld.service
        After=prefetch-rkt-hyperkube.service
        After=prefetch-docker-hyperkube.service
        Requires=flanneld.service
        [Service]
        EnvironmentFile=-/etc/environment
        Environment="KUBELET_ACI=${ hyperkube-image }"
        Environment="KUBELET_VERSION=${ hyperkube-tag }"
        Environment="RKT_OPTS=\
          --volume dns,kind=host,source=/etc/resolv.conf \
          --mount volume=dns,target=/etc/resolv.conf \
          --volume rkt,kind=host,source=/opt/bin/host-rkt \
          --mount volume=rkt,target=/usr/bin/rkt \
          --volume var-lib-rkt,kind=host,source=/var/lib/rkt \
          --mount volume=var-lib-rkt,target=/var/lib/rkt \
          --volume stage,kind=host,source=/tmp \
          --mount volume=stage,target=/tmp \
          --volume var-log,kind=host,source=/var/log \
          --mount volume=var-log,target=/var/log"
        ExecStartPre=/usr/bin/mkdir -p /var/log/containers
        ExecStartPre=/usr/bin/mkdir -p /var/lib/kubelet
        ExecStartPre=/usr/bin/mount --bind /var/lib/kubelet /var/lib/kubelet
        ExecStartPre=/usr/bin/mount --make-shared /var/lib/kubelet
        ExecStart=/usr/lib/coreos/kubelet-wrapper \
          --allow-privileged=true \
          --api-servers=http://127.0.0.1:8080 \
          --cloud-provider=aws \
          --cluster-dns=${ dns-service-ip } \
          --cluster-domain=${ cluster-domain } \
          --kubeconfig=/etc/kubernetes/kubeconfig.yml \
          --pod-manifest-path=/etc/kubernetes/manifests \
          --node-labels node-role.kubernetes.io/master \
          --register-node=true \
          --register-with-taints node-role.kubernetes.io/master='':NoSchedule
        Restart=always
        RestartSec=5
        [Install]
        WantedBy=multi-user.target

  update:
    reboot-strategy: off

write-files:
  - path: /etc/kubernetes/ssl/ca.pem
    content: ${ ca-pem }
    permissions: '0644'
    encoding: base64

  - path: /etc/kubernetes/ssl/k8s-etcd-key.pem
    content: ${ etcd-key }
    encoding: base64
    permissions: '0644'
    owner: root

  - path: /etc/kubernetes/ssl/k8s-etcd.pem
    content: ${ etcd-pem }
    permissions: '0644'
    encoding: base64

  - path: /etc/kubernetes/ssl/k8s-apiserver-key.pem
    content: ${ apiserver-key }
    encoding: base64
    permissions: '0644'
    owner: root

  - path: /etc/kubernetes/ssl/k8s-apiserver.pem
    content: ${ apiserver-pem }
    permissions: '0644'
    encoding: base64

  - path: /etc/kubernetes/ssl/service-account-key.pem
    content: ${ service-account-key }
    permissions: '0644'
    encoding: base64

  - path: /etc/environment
    permissions: 0644
    content: |
      COREOS_PRIVATE_IPV4=$private_ipv4
      ETCD_CA_FILE=/etc/kubernetes/ssl/ca.pem
      ETCD_CERT_FILE=/etc/kubernetes/ssl/k8s-etcd.pem
      ETCD_KEY_FILE=/etc/kubernetes/ssl/k8s-etcd-key.pem
      ETCDCTL_CA_FILE=/etc/kubernetes/ssl/ca.pem
      ETCDCTL_CERT_FILE=/etc/kubernetes/ssl/k8s-etcd.pem
      ETCDCTL_KEY_FILE=/etc/kubernetes/ssl/k8s-etcd-key.pem
      ETCDCTL_ENDPOINT=https://${ fqdn }:2379
      ETCDCTL_DIAL_TIMEOUT=3s
      ETCDCTL_CACERT=/etc/kubernetes/ssl/ca.pem
      ETCDCTL_CERT=/etc/kubernetes/ssl/k8s-etcd.pem
      ETCDCTL_KEY=/etc/kubernetes/ssl/k8s-etcd-key.pem
  - path: /opt/bin/host-rkt
    permissions: 0755
    owner: root:root
    content: |
      #!/bin/sh
      exec nsenter -m -u -i -n -p -t 1 -- /usr/bin/rkt "$@"

  - path: /etc/kubernetes/kubeconfig.yml
    content: |
      apiVersion: v1
      kind: Config
      clusters:
        - name: local
          cluster:
            server: http://127.0.0.1:8080
      users:
        - name: kubelet
      contexts:
        - name: kubelet-context
          context:
            cluster: local
            user: kubelet
      current-context: kubelet-context

  - path: /etc/kubernetes/manifests/kube-apiserver.yml
    content: |
      apiVersion: v1
      kind: Pod
      metadata:
        name: kube-apiserver
        namespace: kube-system
      spec:
        hostNetwork: true
        containers:
        - name: kube-apiserver
          image: ${ hyperkube }
          command:
          - /hyperkube
          - apiserver
          - --storage-backend=${ etcd-storage-backend }
          - --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota
          - --advertise-address=$private_ipv4
          - --apiserver-count=${ apiserver-count }
          - --allow-privileged=true
          - --anonymous-auth=false
          - --client-ca-file=/etc/kubernetes/ssl/ca.pem
          - --cloud-provider=aws
          - --enable-swagger-ui
          - --etcd-cafile=/etc/kubernetes/ssl/ca.pem
          - --etcd-certfile=/etc/kubernetes/ssl/k8s-etcd.pem
          - --etcd-keyfile=/etc/kubernetes/ssl/k8s-etcd-key.pem
          - --etcd-servers=https://etcd.${ internal-tld }:2379
          - --runtime-config=extensions/v1beta1=true,extensions/v1beta1/thirdpartyresources=true,apps/v1beta1=true,batch/v2alpha1=${ enable-api-batch-v2alpha1 }
          - --secure-port=443
          - --service-account-key-file=/etc/kubernetes/ssl/service-account-key.pem
          - --service-account-lookup
          - --service-cluster-ip-range=${ service-cluster-ip-range }
          - --tls-cert-file=/etc/kubernetes/ssl/k8s-apiserver.pem
          - --tls-private-key-file=/etc/kubernetes/ssl/k8s-apiserver-key.pem
          - --v=2
          livenessProbe:
            httpGet:
              host: 127.0.0.1
              port: 8080
              path: /healthz
            initialDelaySeconds: 15
            timeoutSeconds: 15
          ports:
          - containerPort: 443
            hostPort: 443
            name: https
          - containerPort: 8080
            hostPort: 8080
            name: local
          volumeMounts:
          - mountPath: /etc/kubernetes/ssl
            name: ssl-certs-kubernetes
            readOnly: true
          - mountPath: /etc/ssl/certs
            name: ssl-certs-host
            readOnly: true
        volumes:
        - hostPath:
            path: /etc/kubernetes/ssl
          name: ssl-certs-kubernetes
        - hostPath:
            path: /usr/share/ca-certificates
          name: ssl-certs-host

  - path: /etc/kubernetes/manifests/kube-controller-manager.yml
    content: |
      apiVersion: v1
      kind: Pod
      metadata:
        name: kube-controller-manager
        namespace: kube-system
      spec:
        hostNetwork: true
        containers:
        - name: kube-controller-manager
          image: ${ hyperkube }
          command:
          - /hyperkube
          - controller-manager
          - --cloud-provider=aws
          - --leader-elect=true
          - --master=http://127.0.0.1:8080
          - --root-ca-file=/etc/kubernetes/ssl/ca.pem
          - --service-account-private-key-file=/etc/kubernetes/ssl/service-account-key.pem
          resources:
            requests:
              cpu: 200m
          livenessProbe:
            httpGet:
              host: 127.0.0.1
              path: /healthz
              port: 10252
            initialDelaySeconds: 15
            timeoutSeconds: 1
          volumeMounts:
          - mountPath: /etc/kubernetes/ssl
            name: ssl-certs-kubernetes
            readOnly: true
          - mountPath: /etc/ssl/certs
            name: ssl-certs-host
            readOnly: true
        volumes:
        - hostPath:
            path: /etc/kubernetes/ssl
          name: ssl-certs-kubernetes
        - hostPath:
            path: /usr/share/ca-certificates
          name: ssl-certs-host

  - path: /etc/kubernetes/manifests/kube-proxy.yml
    content: |
      apiVersion: v1
      kind: Pod
      metadata:
        name: kube-proxy
        namespace: kube-system
      spec:
        hostNetwork: true
        containers:
        - name: kube-proxy
          image: ${ hyperkube }
          command:
          - /hyperkube
          - proxy
          - --master=http://127.0.0.1:8080
          securityContext:
            privileged: true
          volumeMounts:
          - mountPath: /etc/ssl/certs
            name: ssl-certs-host
            readOnly: true
          - mountPath: /var/run/dbus
            name: dbus
            readOnly: false
        volumes:
        - hostPath:
            path: /usr/share/ca-certificates
          name: ssl-certs-host
        - hostPath:
            path: /var/run/dbus
          name: dbus

  - path: /etc/kubernetes/manifests/kube-scheduler.yml
    content: |
      apiVersion: v1
      kind: Pod
      metadata:
        name: kube-scheduler
        namespace: kube-system
      spec:
        hostNetwork: true
        containers:
        - name: kube-scheduler
          image: ${ hyperkube }
          command:
          - /hyperkube
          - scheduler
          - --leader-elect=true
          - --master=http://127.0.0.1:8080
          resources:
            requests:
              cpu: 100m
          livenessProbe:
            httpGet:
              host: 127.0.0.1
              path: /healthz
              port: 10251
            initialDelaySeconds: 15
            timeoutSeconds: 1

  - path: /etc/logrotate.d/docker-containers
    content: |
      /var/lib/docker/containers/*/*.log {
        rotate 7
        daily
        compress
        size=1M
        missingok
        delaycompress
        copytruncate
      }

  - path: /etc/kubernetes/cni/net.d/10-flannel.conf
    content: |
        {
            "name": "podnet",
            "type": "flannel",
            "delegate": {
                "isDefaultGateway": true
            }
        }

  - path: /opt/bin/download-etcdctl-v3
    permissions: 0755
    owner: root:root
    content: |
      #!/bin/bash -e
      curl -o etcd.tar.gz -SL https://github.com/coreos/etcd/releases/download/v$1/etcd-v$1-linux-amd64.tar.gz
      tar -zxvf etcd.tar.gz etcd-v$1-linux-amd64/etcdctl
      mv etcd-v$1-linux-amd64/etcdctl /opt/bin/etcdctl3
      chmod +x /opt/bin/etcdctl3
      rm -rf  etcd-v$1-linux-amd64 etcd.tar.gz